backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "cards"
    label: "Cards"
    label_singular: "Card"
    files:
      - file: "data/cards.json"
        label: "Cards JSON"
        name: "cardsjson"
        fields:
          - label: "Cards"
            name: "cards"
            widget: "list"
            summary: "{{fields.title}} ({{fields.tag}})"
            